### ISSUE TITLE
Type class instance auto-derivation

### ISSUE THREAD

**Issue by sideeffffect** [avast/scala-server-toolkit#127]
Consider using type class instance auto-derivation tools, like [`derevo`](https://github.com/manatki/derevo) or (maybe even better) [`scalaz-deriving`](https://github.com/scalaz/scalaz-deriving) (which, contrary to the name, doesn't depend on anything ScalaZ)

In our case, it should save us from _a lot_ of boiler-plate code: PureConfig readers and so on.

I was inspired by this article here [Boilerplate-free type class definition](https://medium.com/@maksim.ochenashko/boilerplate-free-type-class-definition-d66e038a8ee8)

**Comment by jakubjanecek** [comment]
What actual problem would it solve for us? I mean I understand what it is used for but I am not aware of too many type class instances so I don't think it would deserve adding the dependency.

**Comment by sideeffffect** [comment]
I would hope that using such a tool would help us get rid of code like this: https://github.com/avast/scala-server-toolkit/blob/master/cassandra-datastax-driver-pureconfig/src/main/scala/com/avast/sst/datastax/pureconfig/ConfigReaders.scala
That's not a nice piece of code -- it's machine level repetition

**Comment by jakubjanecek** [comment]
I've had a look at this and unfortunately I don't think we can use this approach. The problem is that one of the basic design decisions is to have dependencies split into small subprojects. So a configuration case class is in the subproject with the main dependency (e.g. http4s) and the PureConfig `ConfigReader` instances are in another subproject. But we need to write something like `@deriving(ConfigReader)` at the top of the case class which would force us to have the PureConfig dependency (and all the others depending on the typeclasses) in many subprojects.

This is not acceptable at the moment since we do not have to write too much typeclasses (the Cassandra driver is an exception).
