### ISSUE TITLE
Cassandra CqlSession effect wrapper

### ISSUE THREAD

**Issue by sideeffffect** [avast/scala-server-toolkit#88]
The PR https://github.com/avast/scala-server-toolkit/pull/74 added functionality to create an instance of [`com.datastax.oss.driver.api.core.CqlSession`](https://docs.datastax.com/en/drivers/java/4.0/com/datastax/oss/driver/api/core/CqlSession.html)

We should probably not return this object directly, but a wrapper which returns `F[_]: Async` (or whatever), so that it's interoperable with `cats-effect`.

We would need to interop with [`CompletionStage` which is what `CqlSession` returns](https://docs.datastax.com/en/drivers/java/4.0/com/datastax/oss/driver/api/core/CqlSession.html#executeAsync-com.datastax.oss.driver.api.core.cql.Statement-), thus this is blocked on https://github.com/avast/scala-server-toolkit/issues/87

**Comment by jakubjanecek** [comment]
I think this calls for a standalone library which we can use in SST. I don't want to provide such wrappers in SST because the surface of SST would become too large - it is not supposed to become a framework. The main goal of SST is to provide initialization and integration of other libraries. So if there is a library that provides wrapper around `CqlSession` we can create another module and make it work nicely with the whole ecosystem.

**Comment by sideeffffect** [comment]
I see :thinking:
